[template]
sub_templates = ["single-core", "dual-core"]

[placeholders]
gdb_degugger_option = { type = "string", prompt = "GDB debugger configuration" }
target_architecture = { type = "string", prompt = "Target architecture" }
