[hooks]
post = ["post-script.rhai"]


[template]
cargo_generate_version = ">=0.19.0"
ignore = [
    "cargo-generate.toml",
    "cargo-generate-values.toml"
]

[placeholders]
core_0 = { type = "string", prompt = "core 0 label", default = "cortex-m7" }
core_1 = { type = "string", prompt = "core 1 label", default = "cortex-m4" }
