[package]
name = "{{core_1}}"
version = "0.1.0"

# Dependencis for bare metal dev
[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
panic-halt = "0.2.0"
#cortex-m-semihosting = "0.3.3" #un-comment to enable semihosting

