[package]
name = "{{core_1}}"
version = "0.1.0"

# Dependency on the shared library
[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"

# This section specifies custom build scripts, if needed
[build]
script = "build.rs"
