[build]
target = "{{core_1_arch}}"

### Uncomment this to override global settings
#[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "arm-none-eabi-gdb"
#rustflags = [
#  "-C", "link-arg=-Tlink.x",
#]

